[package]
name = "taylorsrus/sound-manager"
description = "Simple manager for sounds on Roblox."
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
